### ISSUE TITLE
Add Tours

### ISSUE THREAD

**Issue by ctoLarsson** [nikgraf/awesome-react-vr#3]
Hi,

I am delighted to announce the (I think) most ambitious launch on React VR to date, LiveTourLab.

I suggest adding a new category Tours, with LiveTourLab as the first entry as below. Then new component repos added that will be part of the tour framework can go there later. Cheers and thank you for creating this list!

(By the way, I tried to make a branch and make a pull request with this myself, but seems permissions aren't set allowing that? Maybe something to consider for you, to save you time. Cheers)

## Tours
* [LiveTourLab](https://github.com/livetourlab/live-tour-lab) - Framework for creating Tours in React VR.

**Comment by nikgraf** [comment]
love it!

I just created a PR https://github.com/nikgraf/awesome-react-vr/pull/4 and merged it. If you want to contribute you need to fork the repository and then create Pull Request.

**Comment by ctoLarsson** [comment]
Superb! Looks great. Thank you and congrats to an important Repo!
